version: '3.8'
services:
  pomello:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pomello
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=development

  postgres:
    image: postgres:14
    container_name: pomello-db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres:
    name: pomello
