apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomello-deployment
  labels:
    app: pomello
spec:
  selector:
    matchLabels:
      app: pomello
  replicas: 1
  template:
    metadata:
      labels:
        app: pomello
    spec:
      serviceAccountName: pomello-sa
      containers: 
        - name: pomello
          image: hongrichard/pomello
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pomello-secret
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: pomello-secret
                  key: JWT_SECRET
            - name: NODE_ENV
              value: production
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.29.0 
          command:
            - "/cloud_sql_proxy"
            - "-instances=datadeque:us-east1:pomello-staging=tcp:5432"
          securityContext:
            runAsNonRoot: true
      imagePullSecrets:
        - name: docker-registry-secret
